{
 "title": "Speedtest Exporter v2",
 "description": "Dashboard for my Speedtest exporter.\r\n\r\nV2 has a results table with:\r\n\r\n- Time\r\n- Speedtest Server ID\r\n- Speedtest Server Name\r\n- Share URL\r\n- Uploaded and downloaded bytes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Downstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "Speed" }
   ],
   "targets": [
    { "expr": "speedtest_download_bytes*8", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Upstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "Speed" }
   ],
   "targets": [
    { "expr": "speedtest_upload_bytes*8", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "speedtest_jittter_seconds", "legendFormat": "Jitter" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "speedtest_servername_info" },
    { "expr": "speedtest_uploadedbytes_bytes", "legendFormat": "Uploaded Bytes" },
    {
     "expr": "speedtest_downloadedbytes_bytes",
     "legendFormat": "Downloaded Bytes"
    },
    { "expr": "speedtest_shareurl_info", "legendFormat": "Share URL" },
    { "expr": "speedtest_serverid_info" }
   ]
  }
 ]
}